import React, { useState } from "react";
import ImageMapper from "react-img-mapper";
import dungeonMap from "./assets/map.png";
import art from "./assets/the-scrape.min.jpeg";
import { RoomData, RoomViewer } from "./components/RoomViewer/RoomViewer";
import { rooms } from "./content/rooms";
import { DraggableToken } from "./components/DraggableToken/DraggableToken";

export interface Position {
  x: number;
  y: number;
}

function App() {
  const [currentRoom, setCurrentRoom] = useState<RoomData | null>(null);
  const [showRoomViewer, setShowRoomViewer] = useState<boolean>(false);

  return (
    <main className="relative w-full flex flex-col 2xl:flex-row gap-4 max-w-screen-2xl m-auto my-4 px-4">
      <figure className="mx-auto">
        <ImageMapper
          map={rooms}
          src={dungeonMap}
          active={true}
          onClick={(e) => {
            const selectedRoom = rooms.areas.find((room) => room.id === e.id);
            setCurrentRoom(selectedRoom || null);
            setShowRoomViewer(true);
          }}
          responsive
          parentWidth={Math.min(800, window.innerWidth - 100)}
        />
      </figure>
      <div className="mx-auto m-4 relative max-w-xl">
        <header className="mb-8">
          <h1 className="font-bungee-shade font-bold text-2xl 2xl:text-6xl 2xl:my-8">
            The Scrape
          </h1>
        </header>
        {!showRoomViewer && (
          <div className="text-lg">
            <img
              className="rounded mb-8"
              src={art}
              alt="adventurers on a mound of trash"
            />
            <p className="mb-4">
              Outside town, there is a massive pit called Tren&apos;tar, but
              locally, it&apos;s referred to as <strong>The Scrape</strong>.
              This is where all the waste generated by a town ends up, tossed
              over the edge. That&apos;s the idea though, for a hundred years,
              the giant heap of trash grows smaller, some say at the bottom
              there&apos;s a giant machine that burns it, others guess that
              it&apos;s continually slipping into an even larger cave system.
            </p>
            <p>
              In the last few weeks however, the pile has stopped shrinking.
            </p>
          </div>
        )}
        <div className="my-8">
          <DraggableToken
            color="bg-slate-300"
            defaultPosition={{ x: 0, y: 0 }}
          />
          <DraggableToken
            defaultPosition={{ x: 25, y: 0 }}
            color="bg-slate-500"
          />
          <DraggableToken
            defaultPosition={{ x: 50, y: 0 }}
            color="bg-slate-800"
          />
        </div>
        {showRoomViewer && (
          <RoomViewer
            roomData={currentRoom}
            closeRoom={() => {
              setShowRoomViewer(false);
            }}
          />
        )}
      </div>
    </main>
  );
}

export default App;
