import React, { useState } from "react";
import ImageMapper from "react-img-mapper";
import dungeonMap from "./assets/map.png";
import art from "./assets/the-scrape.min.jpeg";
import { RoomViewer } from "./components/RoomViewer/RoomViewer";
import { rooms } from "./content/rooms";
import { DraggableToken } from "./components/DraggableToken/DraggableToken";
import { RoomData } from "./content/roomDescriptions";

export interface Position {
  x: number;
  y: number;
}

function App() {
  const [currentRoom, setCurrentRoom] = useState<RoomData | null>(null);
  const [showRoomViewer, setShowRoomViewer] = useState<boolean>(false);

  const getParentWidth = () => {
    // lg
    if (window.innerWidth >= 1024 && window.innerWidth <= 1279) {
      return 500;
    }
    // xl
    if (window.innerWidth >= 1280 && window.innerWidth <= 1535) {
      return 750;
    }
    // 2xl
    if (window.innerWidth >= 1536) {
      return 1000;
    } else {
      return window.innerWidth - 64;
    }
  };

  return (
    <main className="h-screen w-full xl:w-4/5 mx-auto">
      <header className="mx-auto lg:m-4">
        <button
          role="button"
          onClick={() => {
            setShowRoomViewer(false);
          }}
        >
          <h1 className="font-bungee-shade font-bold text-2xl 2xl:text-6xl 2xl:my-8">
            The Scrape
          </h1>
        </button>
      </header>
      <div className="w-full flex flex-col lg:flex-row gap-2">
        <figure className="mx-auto lg:mx-4">
          <ImageMapper
            map={rooms}
            src={dungeonMap}
            active={true}
            onClick={(e) => {
              const selectedRoom = rooms.areas.find((room) => room.id === e.id);
              setCurrentRoom(selectedRoom || null);
              setShowRoomViewer(true);
            }}
            responsive
            parentWidth={getParentWidth()}
          />
          <div className="my-4">
            <DraggableToken
              color="bg-slate-300"
              defaultPosition={{ x: 0, y: 0 }}
            />
            <DraggableToken
              defaultPosition={{ x: 25, y: 0 }}
              color="bg-slate-500"
            />
            <DraggableToken
              defaultPosition={{ x: 50, y: 0 }}
              color="bg-slate-800"
            />
          </div>
        </figure>
        <div className="relative max-w-xl">
          {!showRoomViewer && (
            <div className="hidden lg:block">
              <img
                className="max-h-96 rounded mb-8"
                src={art}
                alt="adventurers on a mound of trash"
              />
              <p className="mb-4">
                Outside town, there is a massive pit called Tren&apos;tar, but
                locally, it&apos;s referred to as <strong>The Scrape</strong>.
                This is where all the waste generated by a town ends up, tossed
                over the edge. That&apos;s the idea though, for a hundred years,
                the giant heap of trash grows smaller, some say at the bottom
                there&apos;s a giant machine that burns it, others guess that
                it&apos;s continually slipping into an even larger cave system.
              </p>
              <p>
                In the last few weeks however, the pile has stopped shrinking.
              </p>
            </div>
          )}

          {showRoomViewer && (
            <RoomViewer
              roomData={currentRoom}
              closeRoom={() => {
                setShowRoomViewer(false);
              }}
            />
          )}
        </div>
      </div>
    </main>
  );
}

export default App;
